= ojosama
:toc: left
:sectnums:

テキストを壱百満天原サロメお嬢様口調に変換して出力します。

== 概要

任意のテキストを壱百満天原サロメお嬢様風の口調風に変換する非公式プログラムです。
コマンドラインとライブラリの2つの方法で使えます。

壱百満天原サロメお嬢様風の口調変換の例を以下に示します。

[options="header"]
|=================
| 変換前 | 変換後
| 〇〇をプレイする | 〇〇をプレイいたしますわ
| ビデオテープはどこで使うんですか | ビデオテープはどちらで使うんですの
| 汚いです | きったねぇですわ
| わたしも使ってました| わたくしも使っておりましたわ
|=================

変換では、単語の品詞や読み、特定の単語の前後にある単語、特定の単語の連続などの変
換ルールを順番に評価して変換しています。

文章に対して形態素解析を行っており、形態素解析ライブラリの https://github.com/ikawaha/kagome[kagome] を使用しています。

== 壱百満天原サロメお嬢様について

以下を参照してください。

* https://www.nijisanji.jp/members/salome-hyakumantenbara[壱百満天原サロメ - にじさんじ公式サイト]
* https://twitter.com/1000000lome[壱百満天原サロメ - Twitter]

== 使い方

=== コマンド

ワンライナーでテキストを変換する場合は、以下のように実行します。

[source,bash]
----
$ ojosama -t これはハーブです
これはおハーブですわ
----

テキストファイルをまるごと変換する場合は、以下のように実行します。

[source,bash]
----
$ ojosama README.adoc
----

=== ライブラリ

Goのコードとして使う場合は以下のように使用します。

[source,go]
----
package main

import (
  "fmt"

  "github.com/jiro4989/ojosama"
)

func main() {
  s := "育ちは一般家庭です"
  text, err := ojosama.Convert(s, nil)
  if err != nil {
    panic(err)
  }
  fmt.Println(text)
}
----

== 注意事項

=== 変換結果について

まだまだ実装途中なので、怪しい変換をする場合があります。

必ずしも、自分のイメージしているお嬢様の口調になっているとは限らないことをご了承ください。

=== プログラムの使用について

壱百満天原サロメお嬢様、及びその所属の にじさんじ や、その関係者、ファンコミュニ
ティの方の迷惑にならないように使ってください。

本プログラムは、にじさんじ所属の壱百満天原サロメお嬢様のキャラクターを題材にした
二次創作の一つです。故に、本プログラムは以下二次創作ガイドラインに従います。

https://event.nijisanji.app/guidelines/[ANYCOLOR二次創作ガイドライン]

本プログラムを使う場合も上記ガイドラインを守ってお使いください。

== 既知のバグ

変換済みの単語を更に変換すると変になります。

[source,bash]
----
$ ojosama -t これはハーブです | ojosama
これはおおハーブですわですわ
----

== 開発者向け

以下のコマンドでビルドします。
実行すると内部で単体テストも実施されるので、とりあえずこれがパスすればOK。

[source,bash]
----
$ make
$ ls -lah ./bin/ojosama
----
